name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: push to release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.1${{ github.run_number }}

  build_ios:
    name: Build Flutter (ios)
    needs: [Flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios

  build_appbundle:
    name: Build Flutter (Android)
    needs: [Flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle

  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx jest --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Osazuwaya/UgRA  
